package it.matteoponzini.utils;

/**
 * @author Matteo Ponzini
 * @version 1.0-ALPHA
 */
public interface ThrowingStrategy {
    /**
     * here is set the die-throwing logy
     * @since 1.0-ALPHA
     * @return number generated by the logic implemented
     */
    Integer throwing();
}
